[package]
name = "datafusion-remote-table"
version = "0.3.0"
edition = "2021"
authors = ["lewiszlw <lewiszlw520@gmail.com>"]
description = "Execute SQL queries on remote databases and make results as datafusion table provider"
keywords = ["SQL", "database"]
license = "MIT"
repository = "https://github.com/systemxlabs/datafusion-remote-table"
readme = "../README.md"

[dependencies]
datafusion = { workspace = true }
datafusion-proto = { workspace = true }
async-trait = "0.1"
futures = "0.3"
async-stream = { version = "0.3" }
chrono = "0.4"
prost = { workspace = true }
derive-with = "0.6"
bb8 = { version = "0.9" }
# Postgres
bb8-postgres = { version = "0.9", features = ["with-chrono-0_4"] }
# MySQL
mysql_async = { version = "0.35", features = [
    "native-tls-tls",
    "chrono",
    "time",
    "bigdecimal",
] }
# Oracle
#bb8-oracle = { version = "0.2", features = ["chrono"]}
oracle = "0.6"
bb8-oracle = { git = "https://github.com/lewiszlw/bb8-oracle.git", branch = "bump-bb8" }

[dev-dependencies]
tokio = { workspace = true }