[workspace]
members = ["integration-tests", "remote-table", "remote-table/gen"]
resolver = "3"

[workspace.dependencies]
datafusion = "46"
datafusion-proto = "46"
tokio = { version = "1", features = ["full"] }
prost = "0.13"
prost-build = "0.13"