[package]
name = "datafusion-remote-table"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "45"
async-trait = "0.1"
futures = "0.3"
sqlx = { version = "0.8.3", default-features = false, features = [
    "mysql",
    "postgres",
    "runtime-tokio",
    "time",
    "chrono",
] }