[workspace]
members = ["integration-tests", "remote-table", "remote-table/gen"]
resolver = "3"

[workspace.dependencies]
datafusion = "47"
datafusion-proto = "47"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.32" }
prost = "0.13"
prost-build = "0.13"