[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion-remote-table = { path = "../remote-table" }
datafusion = "45"
tokio = { version = "1", features = ["full"] }
ctor = "0.4"