[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion-remote-table = { path = "../remote-table" }
datafusion = { workspace = true }
datafusion-proto = { workspace = true }
tokio = { workspace = true }
ctor = "0.4"